Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.):

1. What does Pandas stand for?
 - Panel data or Python Data Analysis

2. What are the 2 collections used in Pandas?
 - Series and Dataframe

3. Name 4 things Pandas can do for us.
 - Data cleansing, data normalization, data visualization, data fill, data inspection, merges and joins, statistical analysis, loading and saving data. 

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
- inplace =  True

5. What is a CSV?
 - comman separated files (values).

6. When cleaning data what values do we not like in our data?
 - you do not want missing values, duplicate records, outliers, inconsistent or incorrect data, data type mismatches, data integrity issues, encoding problems, inconsisten data/time formats, whitespace and formatting issues, scale differences, categorical variable issues, and data entry errors

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

In [43]:
import numpy as np


reshapedArray = np.arange(12, dtype = int).reshape(2, 3, 2)

print(reshapedArray)





[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

In [3]:
array = np.linspace(0, 20, 6)

print(array)

[ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array

In [4]:
deep_copy_array = array.copy()

print(deep_copy_array)

[ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'...
        
        ([[25, 16]])
        ([[11, 2], [13, 4]])
        ([[7, 81], [5, 6], [11, 12]])

In [9]:
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis = 0)

print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


11. Sort 'newArray' in order into 'sortedArray'

In [13]:
sortedArray = np.sort(newArray, axis = 0)

print(np.sort(sortedArray, axis = 0))

[[ 2  6]
 [ 4 11]
 [ 5 12]
 [ 7 13]
 [11 25]
 [16 81]]


12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

In [67]:

arr_reshape = reshapedArray.reshape(4,3)

one, two, three, four = arr_reshape

print(one)
print(two)
print(three) 
print(four)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


13. Combined and sort the following arrays into one called 'comboArray' ...

- one = ([10, 11, 12, 13, 14, 15, 16, 17])
- two = ([20, 21, 22, 23, 24, 25, 26, 27])
- three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [87]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

ComboArray = np.concatenate((one, two, three))
ComboArray = np.sort(ComboArray)

print(ComboArray)


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:

- print sec1 - the 2nd element
- print sec2 - all elements from the 3rd element to the last
- print sec3 - all elements from the 4th to the 14th elements
- print sec4 - the last 6 elements
- print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
- print sec6 - from #20 every even element to the end
- print sec7 - from the last element moving forward, every 5th element.

In [94]:
print("this is the second element", ComboArray[1])
print("all elements from third to last", ComboArray[2:])
print("all elements from the 4th to the 14th", ComboArray[3:15])
print("the last 6 elements", ComboArray[-6:])
print("all elements from 0 up to and including 15, using the negative number method", ComboArray[-28:-10])
print("from #20 every even element to the end", ComboArray[16:])
print("from last element moving forwared every 5th element", ComboArray[-1::-5])

this is the second element 1
all elements from third to last [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
all elements from the 4th to the 14th [ 3  4  5  6  7 10 11 12 13 14 15 16]
the last 6 elements [22 23 24 25 26 27]
all elements from 0 up to and including 15, using the negative number method [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
from #20 every even element to the end [20 21 22 23 24 25 26 27]
from last element moving forwared every 5th element [27 22 15 10  3]


15. Using Series, create a DataFrame that looks like this:

- Ingredients	Quantity	Unit
- Flour	4	cups
- Milk	1	cup
- Eggs	2	large
- Spam	1	can

In [101]:
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name ='ingredients')
Quantity = pd.Series([4, 1, 2, 1], name = 'Quantity')
Unit = pd.Series(['cups', 'cup', 'large', 'can'], name = 'Unit')

df = pd.concat([ingredients, Quantity, Unit], axis = 1)

df

ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

16. Take this data and create a DataFrame named studentData

  {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

In [107]:
df =pd.DataFrame(
    {
        'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
)

df

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [109]:
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
df['deserts'] = deserts

df

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [111]:
df.sort_values(by =['Name', 'address'], inplace = True)

df

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

    df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

In [112]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

(A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [119]:
vegetables =pd.DataFrame(
    {
        'Green vegetables': ['lettuce', 'brocolli', 'spinach'],
        'red vegetables': ['red bellpepper', 'chili peppers', 'tomatoes']
    }
)
vegetables.to_csv('vegetables.csv')

veggies = pd.read_csv('vegetables.csv')
veggies['Fruits'] = ['apple','pear','bananas']
veggies.to_csv('veggies.csv')

